### ISSUE TITLE
Doesn't support utf-8 string on macOS

### ISSUE THREAD

**Issue by fatestigma** [tecosaur/emacs-everywhere#12]
#2 Changed AppleScript `keystroke "v" using command down` to `keystroke (the clipboard as text)`, which breaks the support for CJK, emoji, or special characters.

Could we change it back to paste simulation with "cmd-v"?

**Comment by tecosaur** [comment]
I'm not on Mac, so I don't know what works better — but I'd be happy to if it's an improvement.
@elken is there a reason you changed from `Cmd-v` to typing out the clipboard?

**Comment by elken** [comment]
The previous way wasn't working fully for me

**Comment by tecosaur** [comment]
If different people have different thoughts on this, maybe it's worth making this a setting.

**Comment by elken** [comment]
Just need a bigger sample size

**Comment by d1egoaz** [comment]
Just wanted to confirm that `keystroke (the clipboard as text)` breaks emojis, it works when changed to Command V

**Comment by tecosaur** [comment]
I think this should be fixed now?
