### ISSUE TITLE
No space copied back

### ISSUE THREAD

**Issue by xukai92** [tecosaur/emacs-everywhere#19]
I'm using macOS and emacs-everywhere copies text back to where I triggered it, but without spaces.
For example if I do "hello world" in emacs, what copied back was "helloworld".
Any idea why this happened and how to fix it?

**Comment by tecosaur** [comment]
No idea whatsoever, I haven't heard this before and I haven't got a Mac so I can't exactly test this out...

**Comment by xukai92** [comment]
Is there anything I can do to debug this?

**Comment by xukai92** [comment]
One thing to confirm here is that if I manullay paste by `CMD-v`, the spaces are permitted. So it's something to do with Emacs' calling the system paste.
