### ISSUE TITLE
Frame closes immediately

### ISSUE THREAD

**Issue by ilya-konovalov** [tecosaur/emacs-everywhere#23]
When I run `emacsclient -e '(emacs-everywhere)'` the new empty frame flashes and then is closed immediately. In other client frames I can see that emacs-everywhere- buffer exists.

**Comment by tecosaur** [comment]
Without further information, I don't think I'll be able to locate the error. It would be good to have
1. Steps to reproduce
2. `*Messages*`
3. System information

**Comment by ilya-konovalov** [comment]
Well, I'm afraid I don't have much to show actually.

Steps to reproduce: run `emacsclient -e '(emacs-everywhere)'`. Frame opens and is closed immediately, I'm getting the only output "nil". Nothing in messages.

```
$ emacsclient -e '(emacs-everywhere)'
nil
$
```

System: Gentoo linux, emacs 27.1, xmonad window manager if that's relevant.

**Comment by ilya-konovalov** [comment]
I tried a different version but failed to find a version that worked for me. However when running the version from current master I now see the following message:

```
Emacs Everywhere: error running init hooks, (error Can’t find Hunspell dictionary with a .aff affix file)
```

**Comment by ilya-konovalov** [comment]
Well, apparently this is not emacs-everywhere related:
```
* delete-frame(#<frame Emacs Everywhere :: URxvt — aragaer@stronghold:~/Projects/PA/experimenta… 0x56023c411350>)
  server-delete-client(#<process server <8>>)
  server-sentinel(#<process server <8>> "deleted\n")
  delete-process(#<process server <8>>)
  server-return-error(#<process server <8>> (error "Autoloading file /home/aragaer/.config/emacs/elpa/..."))
  server-execute(#<process server <8>> (("/tmp/emacs-everywhere-n59HDr")) nil nil t #<frame Emacs Everywhere :: URxvt — aragaer@stronghold:~/Projects/PA/experimenta… 0x56023c411350> window-system)
  #f(compiled-function () #<bytecode 0x15808f0fa3d1>)()
  server-execute-continuation(#<process server <8>>)
  server-process-filter(#<process server <8>> "jects/PA/experimental/NLP/receipt-parse\"&_(1190&_2...")
```
