### ISSUE TITLE
Make the delay for clipboard infomation to be processed customized

### ISSUE THREAD

**Issue by HyunggyuJang** [tecosaur/emacs-everywhere#24]
Hi, as I mentioned yesterday&rsquo;s pull request, which you merged, I overjoyed by the fact that finally this amazing facility works!

*However*, unfortunately, the initial contents inserted by `emacs-everywhere` seemed bring up some obsolete one, that is, the one just next to the most recent clipboard contents from time to time.

Furthermore, even with the newly patched pasting mechanism, which relies on emulating `command + v` keystroke, behaves similarly with the initial process described above. It inconsistently spit out some unexpected result.

Today, I was able to narrow down the culprit: The delay time my machine needs for clipboard to be fresh enough might necessitate more than your thought.

So it would be great if you can let the user determine what the best delay time to work with rather than the hard coded one.

Best regards,

&#x2013; **Hyunggyu Jang**

**Comment by tecosaur** [comment]
Sure, that sounds reasonable. It would also be good is you could let me know what's a good value for you.

**Comment by HyunggyuJang** [comment]
Thanks for having interest in my propose! For reference, here is my
local patch:

    @@ -187,6 +187,11 @@ buffers.")
          (org-ctrl-c-ctrl-c)
        (emacs-everywhere-finish)))
    
    (defcustom emacs-everywhere-finsh-delay 0.5
      "Delay for the clipboard contents to be properly set in `emacs-everywhere-finish'."
      :type 'float
      :group 'emacs-everywhere)
    
    (defun emacs-everywhere-finish (&optional abort)
      "Copy buffer content, close emacs-everywhere window, and maybe paste.
    Must only be called within a emacs-everywhere buffer.
    @@ -205,7 +210,7 @@ Never paste content when ABORT is non-nil."
              (write-file buffer-file-name)
              (pp (buffer-string))
              (call-process "xclip" nil nil nil "-selection" "clipboard" buffer-file-name))))
        (sit-for 0.01) ; prevents weird multi-second pause, lets clipboard info propagate
        (sit-for emacs-everywhere-finsh-delay) ; prevents weird multi-second pause, lets clipboard info propagate
        (let ((window-id (emacs-everywhere-app-id emacs-everywhere-current-app)))
          (if (eq system-type 'darwin)
              (call-process "osascript" nil nil nil
    @@ -380,13 +385,24 @@ return windowTitle"))
                            (- x 100)
                            (- y 50))))
    
    (defcustom emacs-everywhere-insert-delay 1
      "Delay for the clipboard contents to be properly set in `emacs-everywhere-insert-selection'."
      :type 'float
      :group 'emacs-everywhere)
    
    (defcustom emacs-everywhere-insert-delay-pre 1
      "Delay for the clipboard contents to be properly set before capturing current selection."
      :type 'float
      :group 'emacs-everywhere)
    
    (defun emacs-everywhere-insert-selection ()
      "Insert the last text selection into the buffer."
      (if (eq system-type 'darwin)
          (progn
            (sit-for emacs-everywhere-insert-delay-pre)
            (call-process "osascript" nil nil nil
                          "-e" "tell application \"System Events\" to keystroke \"c\" using command down")
            (sit-for 0.01) ; lets clipboard info propagate
            (sit-for emacs-everywhere-insert-delay) ; lets clipboard info propagate
            (yank))
        (when-let ((selection (gui-get-selection 'PRIMARY 'UTF8_STRING)))
          (gui-backend-set-selection 'PRIMARY "")

For explanation, I found that I need yet another auxiliary delay before *capturing* the currently selected text since I automated selecting the text in focus using [skhd](https://github.com/koekeishiya/skhd), a hotkey application for macos. For most people who just manually selecting the text in interest might not feel necessary.

**Comment by HyunggyuJang** [comment]
Today, even with my local, I encountered the same problem as before, the instance initiated by `emacs-everywhere` doesn&rsquo;t update its buffer with the most recent clipboard content. So I&rsquo;ve experimented more with several delay values, and find out that no matter what the delay time, `emacs-everywhere` seems to pop up after almost the same time lag, thus, determined `sit-for` might be the culprit.

And read the relevant part of [emacs manual](https://ftp.gnu.org/old-gnu/Manuals/elisp-manual-21-2.8/html_node/elisp_316.html#:~:text=The%20wait%20functions%20are%20designed,time%20to%20view%20the%20display.), and find out we might have had used `sleep-for` rather than `sit-for`, the latter is for redisplaying not for the blocking to ensure to stabilize copy and paste processes.

I&rsquo;ll open an issue related with it, propose a pull request related to it.

**Comment by tecosaur** [comment]
Resolved in #26

**Comment by tecosaur** [comment]
@HyunggyuJang I'm assuming that with that PR a customisable delay is no longer needed? If not, please just reopen this issue :slightly_smiling_face:

**Comment by HyunggyuJang** [comment]
Thanks for your kind words, especially in #26, `magit` is awesome indeed! It teaches me a lot about what was the proper git manipulation.

For the matter of this issue, seems like I can assume there&rsquo;s no more hassle around copy and paste process ;)
