### ISSUE TITLE
How to install this?

### ISSUE THREAD

**Issue by tshrinivasan** [tecosaur/emacs-everywhere#30]
This package is not available in melpa.

How to install this?

**Comment by tecosaur** [comment]
> This package is not available in melpa.

Yes it is: https://melpa.org/#/emacs-everywhere

**Comment by tshrinivasan** [comment]
![image](https://user-images.githubusercontent.com/1268536/127491356-dc524316-f9fb-4988-9747-a470e66d0938.png)

**Comment by tecosaur** [comment]
Thats odd, but if there's something funny with Melpa I don't think I can do anything to fix it here, unfortunately.
