### ISSUE TITLE
Can I save everywhere temp files in a specific directory or org file？

### ISSUE THREAD

**Issue by lroolle** [tecosaur/emacs-everywhere#32]
## What Now?

For macOS with Emacs27, currently emacs-everywhere buffer temp files are located in:

/private/var/folders/pg/...

Like this:
![image](https://user-images.githubusercontent.com/14071051/134529576-ad5aef0f-b92d-4d45-8405-ac7427e68dcf.png)

It is defined by this variable: 
![image](https://user-images.githubusercontent.com/14071051/134534017-42c49593-0b7f-409e-bfae-ff80d5511cbd.png)

## What Expected?

Sometimes I want to re-edit the original unconverted buffer file(org-mode usually converted to markdown for example), re-copy the markdown to org won't be a good choice so that I'll have to find the history everywhere files, it's not so friendly to do this, though you can find it by recent files.

So, If there's any possibility Only to send this everywhere buffer contents to somewhere like an **Inbox** in org-capture, or set a fixed directory to keep all those files(Not a common temporary-file-directory), not only it solves the re-edit problem but also, maybe a good way to track all your ~good ideas~ edited from emacs-everywhere.

**Comment by tecosaur** [comment]
This should now just be a matter of setting `emacs-everywhere-file-dir`.
