### ISSUE TITLE
Two machines, identical config, different beheaviour

### ISSUE THREAD

**Issue by dsteuer** [tecosaur/emacs-everywhere#33]
Hi all! Stumbled upon this package. Installed on desktop (OpenSuse Tumbleweed, emacs 27.2, xfce 4.16.3) and it works like a charm! Took laptop from drawer, same OS, same environment and it does not work.

When I call my shortcut no emacsclient appears, but a small cross and only after clicking an emacsclient window appears. Maybe it tries to get focus somehow. Now I can type in the client, but whatever I type and whatever I do the typed text does not show up anywhere. 

If I start it from a command line "nil" appears after closing the frame.

As far as I can tell focus settings on both machines are identical. 

Any ideas? Now that I know it exists, I want to use it! :-)
Detlef

**Comment by tecosaur** [comment]
Sorry I've taken a while to get back to you. The truth is, your issue confuses me and I'm not sure where to start debugging.
