### ISSUE TITLE
Use markdown-mode by default instead of org?

### ISSUE THREAD

**Issue by ethan-leba** [tecosaur/emacs-everywhere#38]
Though I love org mode as much as the next emacser, the reality is that markdown is *far* more common than org outside of the Emacs ecosystem, which is where emacs-everywhere is intended to be used. So I think it may make more sense to use markdown by default, and specify org apps by title instead.

**Comment by tecosaur** [comment]
Hmm, I'll need more convincing to set this as a default, but you can set this yourself by modifying `emacs-everywhere-init-hooks`.

**Comment by ethan-leba** [comment]
Just asking out of curiosity, but what apps do you use that use org input?

**Comment by tecosaur** [comment]
Nowhere, but thanks to pandoc it gets converted to/from markdown on the fly, which I'm quite happy with.

**Comment by ethan-leba** [comment]
Ah, interesting. How do you have that setup? Is that something that could be added into emacs-everywhere?

**Comment by tecosaur** [comment]
It's already part of emacs-everywhere 🙂.

https://github.com/tecosaur/emacs-everywhere/blob/634924587be831bcb3ca47e97c104216516f9ca9/emacs-everywhere.el#L117-L123

https://github.com/tecosaur/emacs-everywhere/blob/634924587be831bcb3ca47e97c104216516f9ca9/emacs-everywhere.el#L497-L501

If this isn't working as intended, then that's a bug.

**Comment by tecosaur** [comment]
> Hmm, I have pandoc installed but it’s not exporting to MD – from the code you linked it looks like it’s converting md->org but not org->md.

https://github.com/tecosaur/emacs-everywhere/blob/634924587be831bcb3ca47e97c104216516f9ca9/emacs-everywhere.el#L131-L134

https://github.com/tecosaur/emacs-everywhere/blob/634924587be831bcb3ca47e97c104216516f9ca9/emacs-everywhere.el#L539-L547

> Maybe using emacs-everywhere-init-hooks would be the best way to achieve the same

Yes, it would.

```elisp
(remove-hook 'emacs-everywhere-init-hooks #'emacs-everywhere-major-mode-org-or-markdown) ; or #'org-mode if that's what's present
(add-hook 'emacs-everywhere-init-hooks #'gfm-mode)
```

**Comment by d1egoaz** [comment]
> Yes, it would.

great, thanks!
