### ISSUE TITLE
Error in post-command-hook

### ISSUE THREAD

**Issue by iT-Boyer** [tecosaur/emacs-everywhere#47]
using the everywhere module in Doom emacs。
when complete with C-c C-c，show debug error：
```
Error in post-command-hook (winner-save-old-configurations): (wrong-type-argument frame-live-p #<dead frame  0x13d287800>)
```

**Comment by tecosaur** [comment]
A proper backtrace is needed, else I don't see how this is an emacs-everywhere issue.
