### ISSUE TITLE
Feature request: rofi in elisp

### ISSUE THREAD

**Issue by QiangF** [tecosaur/emacs-everywhere#55]
Emacs has easy filter and fuzzy match with packages like ivy, and it has good support for different languages. For comparison, rofi doesn't support CJK language (chinese, korean and japanese). Emacs should not be just an editor, emacs has everything.

To make a clipmenu like feature with emacs, add app laucher later, there is a good start point:
https://sr.ht/~trs-80/rofi-in-elisp

**Comment by tecosaur** [comment]
This sounds out of scope.
