### ISSUE TITLE
Specify Frame Options

### ISSUE THREAD

**Issue by theherk** [tecosaur/emacs-everywhere#60]
I'd like to control how the everywhere frame opens. It seems the eval statement actually launches the frame which means running with `/opt/homebrew/bin/emacsclient --eval "(progn (emacs-everywhere) (toggle-frame-maximized))"` doesn't work as hoped.

On my macos machine the popup launches mostly off the window every time, and I can't sort how to configure this without access to frame options.

Any help is appreciated.

**Comment by QiangF** [comment]
The position is set in "emacs-everywhere-set-frame-position".
Maybe just put the frame at the bottom of the current display.

**Comment by QiangF** [comment]
I am settled with this:
     (require 'frame-cmds)
     (defun emacs-everywhere-set-frame-position ()
       "Set the size and position of the emacs-everywhere frame."
       (sleep-for 0.02)
       (move-frame-to-screen-bottom 0))

**Comment by theherk** [comment]
Thanks for the response, @tecosaur. Unfortunately, the contents of this function you mention are precisely what I seek. I'm not sure why this is an invalid question. I'm sure there is a good reason the frame launches out of view every time, but I'm looking for how to resolve that.

**Comment by tecosaur** [comment]
This is invalid in the sense that it's trying to use emacs-everywhere in a way it's not designed to handle.

Re: the behaviour you're trying to seek:
- The behaviour you're seeing is from `emacs-everywhere-set-frame-position`
- `emacs-everywhere-set-frame-position` is only run because it is in `emacs-everywhere-init-hooks`
- you can remove `emacs-everywhere-set-frame-position` from `emacs-everywhere-init-hooks` and add your own function implementing whatever behaviour you want

**Comment by theherk** [comment]
I suspect I am out of my depth here. I am not directly making any calls to `emacs-everywhere-set-frame-position`, so I presume it is happening in the doom module somewhere. I'm not sure how to get the behavior where it is on the screen, but that is a shortcoming of mine. Thanks for your time.

**Comment by tecosaur** [comment]
> - `emacs-everywhere-set-frame-position` is only run because it is in `emacs-everywhere-init-hooks`

**Comment by theherk** [comment]
Just to clarify, when you say "This is invalid in the sense that it's trying to use emacs-everywhere in a way it's not designed to handle," I assume that doesn't mean this is not designed to handle being on screen, but that is actually the only thing I mean to learn. I genuinely not clear on what I've done wrong here.

**Comment by tecosaur** [comment]
"invalid" because tweaking the created frame properties via `--eval` is not expected.

**Comment by theherk** [comment]
Cool. Am I barking up the wrong tree then by asking, what is the designed method for having this be on screen?

**Comment by tecosaur** [comment]
IDK what you mean by "on screen", but:

> you can remove `emacs-everywhere-set-frame-position` from `emacs-everywhere-init-hooks` and add your own function implementing whatever behaviour you want

**Comment by theherk** [comment]
By on screen, I simply mean not off the screen as shown here.

<img width="1440" alt="Screenshot 2022-08-31 at 19 27 41" src="https://user-images.githubusercontent.com/3605078/187741833-4a3cec24-faad-4dc3-bbca-0d4755164acd.png">

Nevertheless, it seems clear that the option is to learn how to write the function you reference. Thank you.

**Comment by tecosaur** [comment]
Yep, so I'd use that function as a reference and tweak it so it works better for you. If there's a heuristic that you think generally improves the positioning logic, feel free to open a PR :slightly_smiling_face:.
