### ISSUE TITLE
void-function emacs-everywhere-major-mode-function

### ISSUE THREAD

**Issue by wztdream** [tecosaur/emacs-everywhere#63]
Hi,

I am using spacemacs on ubuntu22.04. I find the selected text are not send to emacs when
invoke emacs-everywhere. I turn on debug on error, it shows below backtrace:

    Debugger entered--Lisp error: (void-function emacs-everywhere-major-mode-function)
      emacs-everywhere-major-mode-function()
      run-hooks(emacs-everywhere-init-hooks)
      emacs-everywhere-initialise()
      server-visit-files((("/tmp/emacs-everywhere-20220826-151853-firefox")) #<process server <7>> nil)
      server-execute(#<process server <7>> (("/tmp/emacs-everywhere-20220826-151853-firefox")) nil nil t #<frame Emacs Everywhere :: firefox — Issues - tecosaur/emacs-everywhere - GitHub 0x55e56e8afab0> window-system)
      #f(compiled-function () #<bytecode 0x882abec2709b313>)()
      server-execute-continuation(#<process server <7>>)
      server-process-filter(#<process server <7>> "-env GJS_DEBUG_TOPICS=JS&_ERROR;JS&_LOG -env CONDA...")

The value of `emacs-everywhere-major-mode-function` is: `org-mode`

But if I directly define `emacs-everywhere-major-mode-function` it works fine:

```elisp
    (defun emacs-everywhere-major-mode-function ()
      (org-mode)
      )
```

**Comment by tecosaur** [comment]
Fixed in c3d5d1accec20c79c79dbee316cd846973207771.
