### ISSUE TITLE
Wrong type argument: commandp, emacs-everywhere--app-info-linux when C-c C-c in everywhere window

### ISSUE THREAD

**Issue by cashpw** [tecosaur/emacs-everywhere#75]
I get the following error when I press `C-c C-c` to finalize text in an everywhere buffer: `Wrong type argument: commandp, emacs-everywhere--app-info-linux`. I suspect this was introduced in [the latest commit on line 322](https://github.com/tecosaur/emacs-everywhere/commit/fbeff19825336777dccaefedf3f376dd622cd294#diff-617f985a4a24c251cbcd3941aa388919ec5eee12d9b60d4c860f3c6ef5e81e65R322). I was able to return to previous `C-c C-c` behavior by adding the following to my config:

    (map!
     :map emacs-everywhere-mode-map
     "C-c C-c" #'emacs-everywhere--finish-or-ctrl-c-ctrl-c)

**Comment by tecosaur** [comment]
Ooops, that's a pretty obvious mistake. Fixed in bc91164151ab012ff884af92321557f9b37eeed1.

**Comment by tecosaur** [comment]
Thanks for the report!
