### ISSUE TITLE
If the buffer is emptied, the original text area doesn't

### ISSUE THREAD

**Issue by finex** [tecosaur/emacs-everywhere#8]
Hi, I'm giving a first try to Emacs Everywhere (I'm using it to write this issue). It looks interesting but I've found a couple of problems. One is this issue, here is the steps to reproduce:

1. write something on a textbox inside firefox
2. select all
3. open emacs everywhere (so you will get the existing content into the emacs buffer)
4. delete all the content
5. go back to firefox `C-c C-c`

Now I will expect that the firefox textbox is emptied. Instead is not. It looks that if the buffer is empty, the original text is not synced.

Is this a wanted behaviour or a bug?

Thanks! :-)

**Comment by finex** [comment]
P.S: step 3 is not always true, on Firefox a simple `CTRL+A` is enough. Instead on other software (I've tried Kate), you need to select all the text with the mouse, otherwise emacs everywhere will start with an empty buffer)

**Comment by tecosaur** [comment]
Emacs everywhere works by copying to the clipboard, I think the underlying cause of this behaviour is that when trying to paste an empty clipboard, at least in a quick test, nothing happens.

In other words, this has more to do with how the system clipboard works than Emacs Everywhere.

**Comment by tecosaur** [comment]
I'll re-open the issue if it seems that something can actually be done about this.

**Comment by finex** [comment]
Thank you! If you have some update I can help with tests :-)
