### ISSUE TITLE
emacs-everywhere--app-info-osx: symbol undefined in version 20240416.354?

### ISSUE THREAD

**Issue by vincentkam** [tecosaur/emacs-everywhere#87]
Emacs version: GNU Emacs 30.0.50 (build 1, aarch64-apple-darwin23.2.0, NS appkit-2487.30 Version 14.2.1 (Build 23C71)) of 2024-02-14
emacs-everywhere version: 20240416.354  
I also have magit installed: version 20240415.1557. (https://github.com/magit/magit).

When I edit a file in Emacs, invoke Magit via `C-x g`, and then try to create a commit and edit the commit message via (`c, c`), I see the following error message:

`Git failed ... [Hit $ to see buffer magit-process: tilde for details]`

When I hit tilde, I then see this:
`Symbol’s function definition is void: emacs-everywhere--app-info-osx`

If I uninstall `emacs-everywhere`, I am able to create and edit the commit message as usual. 

I expect that I'm simply doing something wrong, but I did have `emacs-everywhere` from months and months ago and never had any issues, so perhaps there's a chance that it's something to do with version `20240416.354`?

**Comment by tecosaur** [comment]
Thanks for the report! There's some work currently going on to make Wayland support a bit easier, and it seems like you've been caught out by an introduced bug in the process.

I'll give this a look, and see if I can work out what's happening.

**Comment by tecosaur** [comment]
Oh oops, that's a pretty obvious mistake. Should be fixed in f8c571475905273d09acb11885bccaf8bbbacbae.

**Comment by vincentkam** [comment]
Thanks @tecosaur!!
