### ISSUE TITLE
Temporary files are world-readable

### ISSUE THREAD

**Issue by aluaces** [tecosaur/emacs-everywhere#89]
Hi, while I really do appreciate that emacs-everywhere makes a backup of the contents, I realized that they are created as world-readable `rw-rw-r`, so anyone in the system can read what I am typing.

I suppose there should be a way in elisp of opening the file with the appropriate permissions, but currently I don't know how to do it.

**Comment by tecosaur** [comment]
Ah good point, why don't we see if we can make them `rw-------` instead.

**Comment by aluaces** [comment]
That would be perfect!

**Comment by tecosaur** [comment]
Hopefully this is better as of #90.
