### ISSUE TITLE
Differences between emacs-everywhere and emacs-anywhere

### ISSUE THREAD

**Issue by finex** [tecosaur/emacs-everywhere#9]
Hi, on the emacs-everywhere README it should be added how this project is different from emacs-anywhere since it reimplements it. Why should I choose emacs-everywhere instead of emacs-anywhere? Thanks for your feedback!

**Comment by tecosaur** [comment]
The simple answer is this:

### Emacs Anywhere
![image](https://user-images.githubusercontent.com/20903656/108744300-bf3c7a80-7574-11eb-8ea3-5cffba6d9e03.png)

### Emacs Everywhere
![image](https://user-images.githubusercontent.com/20903656/108744339-c6fc1f00-7574-11eb-8498-b4ed31be187e.png)

Related to this, Emacs Everywhere can actually be installed via MELPA, as opposed to an ad-hoc shell script.

Other than that I think Emacs Everywhere has some nicer design elements — such as using a minor-mode and buffer-local variables to remember which application it was called to and return to it. As a result:

-   Emacs Everywhere can have multiple instances open at once
-   Closing another random frame that's part of the same daemon won't cause an Emacs Everywhere buffer to prematurely exit
-   Should be nicer to modify/customise

Then there are a bunch of nice utilities provided as hooks, and it should be rather easy to add your own. I was accomplishing the same effect before with Emacs Anywhere in my personal usage, but it was a lot hackier.

Emacs Everywhere also doesn't `cat` the elisp file into an `--eval` argument of the `emacsclient` command every time it's called, which I find somewhat nicer 😅.

**Comment by tecosaur** [comment]
I probably won't put this on the readme, but I'll leave this issue so it can be linked to as an answer to that question.

**Comment by finex** [comment]
Ok, eventually put a link to the issue as reference. Thank you! :-)
